---
# https://docs.docker.com/engine/install/centos/

- name: Remove old docker
  ansible.builtin.dnf:
    name: 
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Install dnf-plugins-core
  ansible.builtin.dnf:
    name: 
      - dnf-plugins-core
    state: present
    update_cache: yes

- name: Add Docker repository into sources list
  ansible.builtin.shell: |
    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker
  ansible.builtin.dnf:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin 
    state: present
    update_cache: yes
