---
#
# Install Docker engine
# 

- name: Install Docker on Ubuntu
  ansible.builtin.include_tasks:
    file: docker-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker on Debian 
  ansible.builtin.include_tasks:
    file: docker-debian.yml
  when: ansible_distribution == 'Debian'

- name: Install Docker on Rocky 
  ansible.builtin.include_tasks:
    file: docker-centos.yml
  when: ansible_distribution == 'Rocky'

- name: Post install 
  ansible.builtin.include_tasks:
    file: post-install.yml
